# Generated by Django 5.1.3 on 2024-11-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.IntegerField(default=123456789),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='sent', max_length=100),
        ),
    ]
