# Generated by Django 5.1.3 on 2024-11-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_timestamp_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(default=1),
        ),
    ]
