# Generated by Django 5.1.3 on 2024-12-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='human_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='size',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
