# Generated by Django 5.1.3 on 2024-12-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message_human_size_message_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='extension',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
