# Generated by Django 5.1.3 on 2024-12-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefinance',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
