# Generated by Django 5.1.3 on 2024-12-07 03:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chargefinance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefinance',
            name='activity_or_project',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='chargefinance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
