# Generated by Django 5.1.3 on 2024-12-07 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chargefinance_activity_or_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
