# Generated by Django 5.1.3 on 2024-12-09 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_invoice_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for',
            field=models.ManyToManyField(related_name='my_message_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
