# Generated by Django 5.1.3 on 2024-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_goal_portfolio_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='chat_rooms',
            field=models.ManyToManyField(related_name='project_chat_rooms', to='app.chatroom'),
        ),
    ]
