# Generated by Django 5.1.3 on 2024-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_project_chat_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
