# Generated by Django 5.1.3 on 2024-12-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sections',
            field=models.ManyToManyField(related_name='projects', to='app.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tasks',
            field=models.ManyToManyField(related_name='sections', to='app.task'),
        ),
    ]
