# Generated by Django 5.1.3 on 2024-12-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_project_sections_alter_section_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='fa fa-rocket', max_length=30, null=True),
        ),
    ]
