# Generated by Django 5.1.3 on 2024-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notification_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='show_data',
            field=models.BooleanField(default=True),
        ),
    ]
