# Generated by Django 5.1.3 on 2024-12-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_invoice_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_poster',
            field=models.ImageField(null=True, upload_to='video_posters'),
        ),
    ]
