# Generated by Django 5.1.3 on 2024-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_message_video_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='video_posters'),
        ),
    ]
