# Generated by Django 5.1.3 on 2024-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_message_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecondinfo',
            name='init_code',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
