# Generated by Django 5.1.3 on 2024-12-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usersecondinfo_init_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
