# Generated by Django 5.1.3 on 2024-12-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_project_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='key',
        ),
    ]
