# Generated by Django 5.1.3 on 2024-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_project_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='key',
            new_name='project_key',
        ),
    ]
