# Generated by Django 5.1.3 on 2024-12-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_key_project_project_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteLifeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(default=True)),
            ],
        ),
    ]
