
from .views import *
from django.urls import path


app_name = 'app'

urlpatterns = [
    path("login/", auth, name="auth"),
    path("", home, name="home"),
    path("my_info/", get_my_info, name="my-info"),
    path('get_my_projects/', get_my_projects, name="get_my_projects"),
    path('logout/', logout_view, name="logout"),
    path("create_new_project/", create_new_project, name="create_new_project"),
    path("get_project_data/<int:pk>/", get_project_data, name="get_project_data"),
    path("edit_project_attribute/", edit_project_attribute, name="edit_project_attribute"),
    path("invite_user_to_join_project/", invite_user_to_join_project, name='invite_user_to_join_project'),
    path('update_token/p/95e51bb26eb0171bac1755216457c043/<str:key>/<str:bool>/', update_token, name='update_token'),
    path('update_profile/', update_profile, name="update_profile"),
    path('add_section/', add_section, name='add_section'),
    path("add_task/", add_task, name='add_task'),
    path('project/upload_file/', upload_project_file, name='upload_project_file'),
    path('project/notes/', add_project_note, name="add_project_note"),
    path('get_my_notes/', get_my_notes, name="get_my_notes"),
    path("personal/notes/", personal_note, name='personal_note'),
    path('update_task_name/', update_task_name, name='update_task_name'),
    path('update_task_des/', update_task_des, name='update_task_des'),
    path("update_task_status/", update_task_status, name='update_task_status'),
    path('post_comment/', post_comment, name='post_comment'),
    path("delete_section/", delete_section, name='delete_section'),
    path("mark_all_task_done/", mark_all_task_done, name='mark_all_task_done'),
    path('edit_client_info/', edit_client_info, name="edit_client_info"),
    path("mark_one_task_as_done/", mark_one_task_as_done, name='mark_one_task_as_done'),
    path("delete_task/", delete_task, name='delete_task'),
    path("duplicate_task/", duplicate_task, name='duplicate_task'),
    path("invite_user_into/", invite_user_into, name='invite_user_into'),
    path('edit_note/', edit_note, name='edit_note'),
    path('create_conversation/', create_conversation, name='create_conversation'),
    path('send_message/', send_message, name='send_message'),
    path("add_invoice/", add_invoice, name='add_invoice'),
    path("add_charge_finance/", add_charge_finance, name="add_charge_finance"),
    path('change_invoice_status/', change_invoice_status, name='change_invoice_status'),
    path('delete_invoice/', delete_invoice, name='delete_invoice'),
    path('search/', search, name='search'),
    path('delete_message_for_me/', delete_message_for_me, name='delete_message_for_me'),
    path('delete_for_everyone/', delete_for_everyone, name='delete_for_everyone'),
    path("add_personal_task/", add_personal_task, name='add_personal_task'),
    path("create_repport/", create_repport, name="create_repport"),
    path('create_new_portfolio/', create_new_portfolio, name='create_new_portfolio'),
    path('create_goal/', create_goal, name='create_goal'),
    path('vote_easy/', vote_easy, name='vote_easy'),
    path('vote_diff/', vote_diff, name='vote_diff'),
    path('vote_impossible/', vote_impossible, name='vote_impossible'),
    path('delete_perso_task/', delete_perso_task, name='delete_perso_task'),
    path('done_perso_task/', done_perso_task, name='done_perso_task'),
    path('send_invoice_email/', send_invoice_email, name='send_invoice_email'),
    path('create_group_chat/', create_group_chat, name='create_group_chat'),
    path('password_initialisation/<str:key>/', init, name='init'),
    path('sign_up/<str:key>/', sign_up, name='sign_up'),
    path('sign_up/', just_sign_up, name='just_sign_up'),
    path('delete_project/<str:id>/', delete_project, name='delete_project'),
    path('delete_conversation/<str:room>/', delete_conversation, name='delete_conversation'),
    path('change_password/', change_password, name='change_password'),
    path('password_init/', password_init, name='password_init'),
    path('get_recovery_code/', get_recovery_code, name='get_recovery_code'),
    path('check_code/', check_code, name='check_code'),
    path('delete_project_file/<int:id>/', delete_project_file, name='delete_project_file'),
    path('change_recovery_password/', change_recovery_password, name='change_recovery_password'),
]